[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Backend (Railway) URL for API and Socket.IO
  VITE_BACKEND_URL = "https://ludo-new-production.up.railway.app"
  # Supabase project URL
  VITE_SUPABASE_URL = "https://absrtypgdqjblourhlgm.supabase.co"
  # Supabase anon key
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFic3J0eXBnZHFqYmxvdXJobGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTExMjAsImV4cCI6MjA2MTE4NzEyMH0.SUsX26tHNDMYARdWVAsKwlaFlZbXzgMfGZ666cxooIQ"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set proper MIME types for JavaScript modules
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# No cache for HTML and service worker
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, no-cache"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "text/javascript"