[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Backend (Railway) URL for API and Socket.IO
  VITE_BACKEND_URL = "https://ludo-new-production.up.railway.app"
  # Supabase project URL
  VITE_SUPABASE_URL = "https://absrtypgdqjblourhlgm.supabase.co"
  # Supabase anon key
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFic3J0eXBnZHFqYmxvdXJobGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTExMjAsImV4cCI6MjA2MTE4NzEyMH0.SUsX26tHNDMYARdWVAsKwlaFlZbXzgMfGZ666cxooIQ"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 